options:
  machineType: "N1_HIGHCPU_32"
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--target', 'ipfs-node',
         '-t', 'gcr.io/$PROJECT_ID/ipfs-node:1',
         '-f', 'docker/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--target', 'graph-node',
         '--build-arg', 'COMMIT_SHA=$COMMIT_SHA',
         '--build-arg', 'REPO_NAME=$REPO_NAME',
         '--build-arg', 'BRANCH_NAME=$BRANCH_NAME',
         '--build-arg', 'TAG_NAME=$TAG_NAME',
         '--build-arg', 'KETTLE_POSTGRES_PASSWORD=$$PKETTLE_POSTGRES_PASSWORD',
         '-t', 'gcr.io/$PROJECT_ID/graph-node:1',
         '-f', 'docker/Dockerfile', '.']
  secretEnv: ['KETTLE_POSTGRES_PASSWORD']
images:
  - 'gcr.io/$PROJECT_ID/ipfs-node:1'
  - 'gcr.io/$PROJECT_ID/graph-node:1'
timeout: 10000s
availableSecrets:
  secretManager:
  - versionName: projects/kettle-399420/secrets/KETTLE_POSTGRES_PASSWORD/versions/1
    env: 'KETTLE_POSTGRES_PASSWORD'
